gaearon/overreacted.io

package.json
src/templates/blog-post.js

Before I started reading your first post on `overreacted.io`, I wanted to know how long your article is.
I thought, this PR would be a great addon for the site, but I let you decide that! 🙂 
Thanks for everything you do around `React`! You really care about us, the end users of `React`. ❤️ 
Ciao

Add reading time

---

src/components/Bio.js
src/components/Footer.js
src/components/Layout.js

Link to RSS feed is added to the end of Bio component.

add rss feed link in Bio

---

src/utils/theme.css

The behaviour of code block round corners is a bit weird. Also the horizontal scrollbar doesn't look nice. Made some improvements to this problem:
Hope it looks better!

fix code block round corner display when horizontal scrollbar appears

---

src/pages/how-does-react-tell-a-class-from-a-function.md

I really enjoyed this article, thank you for writing it!
I noticed a small typo in one paragraph, I think removing the extra "no" fixes it.

Fix small typo

---

src/pages/my-wishlist-for-hot-reloading.md

Fix "shouldn't shouldn't" in my-wishlist-for-hot-reloading.md

---

package.json
src/pages/why-do-hooks-rely-on-call-order.md
yarn.lock

Fix images are broken in the build

---

src/utils/theme.css

Disable ligatures on code snippets

---

src/pages/things-i-dont-know-as-of-2018.md

Change the word order of a sentence.

Fix grammar in things-i-dont-know-as-of-2018.md

---

src/components/Signup.js

This should open a different keyboard setup on mobile devices, better experience.

Signup - change to input type email for better mobile experience

---

gatsby-config.js
package.json
src/utils/theme.css
yarn.lock

This allows people to link to e.g. https://overreacted.io/why-do-hooks-rely-on-call-order/#flaw-1-cant-extract-a-custom-hook

Add anchor links to blog post headers

---

src/components/SEO.js
src/pages/index.js
src/templates/blog-post.js

Set language dynamically, pass from home and post

---

src/pages/optimized-for-change.es.md
src/pages/optimized-for-change.md
src/utils/i18n.js

I would love to contribute with Spanish translations for all of your posts. I started with this one simply because it was the shortest.

Added Spanish translation for "Optimized for change"

---

src/pages/things-i-dont-know-as-of-2018.ko.md
src/pages/things-i-dont-know-as-of-2018.md
src/pages/things-i-dont-know-as-of-2018.sv.md
src/pages/things-i-dont-know-as-of-2018.zh-hant.md
src/utils/i18n.js

Damn, there are so many tech words that you don't even reflect on day to day since even us swedes speak english amongst ourselves at work. This was a learning experience!

Added Swedish translation

---

src/pages/things-i-dont-know-as-of-2018.sv.md

Forgot to add title and spoiler in my last PR.

Add Swedish title and spoiler

---

languages.js
src/pages/why-do-we-write-super-props.hu.md
src/utils/i18n.js

I added Hungarian language support + translated the Why Do We Write super(props)? article.

Add Hungarian language and one article

---

src/pages/optimized-for-change.fr.md

cc @telaoumatenyanis 
Sorry for my tweet, I stumbled onto the screenshot because of the "gouffre du succès" which I couldn't understand without the link.
What do you think of those changes?

Modification of french translation for optimized-for-change

---

src/pages/things-i-dont-know-as-of-2018.es.md
src/pages/things-i-dont-know-as-of-2018.ko.md
src/pages/things-i-dont-know-as-of-2018.md
src/pages/things-i-dont-know-as-of-2018.pt-br.md
src/pages/things-i-dont-know-as-of-2018.sv.md
src/pages/things-i-dont-know-as-of-2018.zh-hant.md

We did an effort at @TallerWebSolutions to translate "Things I Don’t Know as of 2018" post. We found it has many meaning in our company culture, and we thank you for this very motivational and encouraging content!
Ps.: most of the translation work was put-up by a junior developer of ours @ericvvf, so the commit goes in his name ;)

Added pt-br (Brazilian Portuguese) for "things-i-dont-know-as-of-2018"

---

src/templates/blog-post.js

Tiny optimization for better looking the top of posts. Comparison:

Increase indentation between title and date

---

src/pages/my-wishlist-for-hot-reloading/index.fr.md
src/pages/my-wishlist-for-hot-reloading/index.md

*(Side note: I took the liberty of updating the stale redux-docs ref in the original English article as well)*

copy(fr): French L10n for the hot-reloading article

---

src/pages/why-do-we-write-super-props/index.es.md
src/pages/why-do-we-write-super-props/index.fr.md
src/pages/why-do-we-write-super-props/index.hu.md
src/pages/why-do-we-write-super-props/index.it.md
src/pages/why-do-we-write-super-props/index.ja.md
src/pages/why-do-we-write-super-props/index.md
src/pages/why-do-we-write-super-props/index.my.md
src/pages/why-do-we-write-super-props/index.pt-br.md
src/pages/why-do-we-write-super-props/index.th.md
src/pages/why-do-we-write-super-props/index.tr.md
src/pages/why-do-we-write-super-props/index.vi.md
src/utils/i18n.js

Hi Dan! I have just translated your first article into Burmese.

Add Burmese translation of why-do-we-write-super-props

---

README.md

Changed the Contributing Translations section in the README.md according to the recent changes

New rules for contributing translations

---

src/pages/why-isnt-x-a-hook/index.md

I dunno if this was intentional, but I'm thinking not 🙂

Remove duplicate "useShouldComponentUpdate" example

---

src/pages/preparing-for-tech-talk-part-1-motivation/index.fr.md
src/pages/preparing-for-tech-talk-part-1-motivation/index.md

@gaearon I took the liberty to fix a word in the alt text of the second image for the original article (was "concentration" when it should have been "conversations")

French version of the “Preparing for a tech talk, part 1: Motivations" article

---

src/pages/things-i-dont-know-as-of-2018/index.fr.md

This restores mergability from #169, that was unduly closed with the fork deleted, hence could not be reopened.

French version of the “Things I don’t know as of 2018” article

---

src/pages/optimized-for-change/index.de.md
src/utils/i18n.js

This pull request contains a translation of the article "Optimized for Change" to German.

Add German translation of "Optimized for Change"

---

src/pages/how-does-react-tell-a-class-from-a-function/index.sk.md

This pull request contains a Slovak translation of [How Does React Tell a Class from a Function?](https://overreacted.io/how-does-react-tell-a-class-from-a-function/)

Translate to Slovak: How Does React Tell a Class from a Function?

---

src/pages/react-as-a-ui-runtime/index.md

It might not be obvious where the helper is coming from.

Change `memo` to `React.memo`

---

src/pages/making-setinterval-declarative-with-react-hooks/index.md

Rest of the post doesnt have this argument used and it seems to me its not actually needed

Remove dependency array from "remembering" effect

---

src/pages/why-isnt-x-a-hook/index.it.md

I tried to stay as close to the original post as possible, obviously a few things needed rephrasing or the sentence would read way too long in Italian. Also I did not update the file in `utils` to add Italian as someone already did that.

Italian translation of "Why isn't X a hook?"

---

src/pages/how-does-react-tell-a-class-from-a-function/index.hu.md

My previous PR accidentally deleted the index.md file, sorry for that. I closed that down. Now this one should be fine.

Translate to Hungarian: How Does React Tell a Class from a Function?

---

src/pages/why-do-we-write-super-props/index.nl.md
src/utils/i18n.js
yarn.lock

I wrote a Dutch translation for the post 'Why Do We Write super(props)'.

Add dutch translation to 'why do we write super props'

---

src/pages/the-bug-o-notation/index.fr.md
src/pages/the-bug-o-notation/index.md

❌ ¯\\_(ツ)_/¯ 🙅‍♀️
👍 ¯\\\_(ツ)\_/¯ 💁‍♀️

Give shruggie its arms back

---

src/pages/preparing-for-tech-talk-part-1-motivation/index.pt-br.md

There were some spelling mistakes in the Portuguese version of "Preparing for a Tech Talk, Part 1: Motivation", so I corrected them.

Some portuguese spelling corrections

---

src/pages/why-do-we-write-super-props/index.sr.md
src/utils/i18n.js

Apparently I read all the posts way too fast to notice that translations are being contributed now :thinking:

i18n(sr): why do we write super props

---

src/components/Signup.js

Fix typo: fontsize -> fontSize

---

src/pages/how-does-react-tell-a-class-from-a-function/index.md

Well, I'm not a native speaker, so I'm not entirely sure if this is some slang or idiomatic expression but even after some research, I keep thinking it's missing a word :thinking:

Add a missing word

---

src/pages/the-bug-o-notation/index.ja.md

Hello!
This pull request contains a translation of the article "The “Bug-O” Notation" to Japanese.
Thanks.

Translate to Japanese:The “Bug-O” Notation

---

src/templates/blog-index.js

Hello @gaearon,
I have made changes to improve buld time and optimize the query for index pages

Added filtering by lang key to query 

---

src/pages/how-does-react-tell-a-class-from-a-function/index.zh-hans.md

This pull request contains a translation of the article "How does React tell a class from a function" to Simplified Chinese.

Translate to Simplified Chinese: How does React tell a class from a function

---

src/pages/fix-like-no-ones-watching/index.es.md

This PR is basically a friendlier writing with my internal translation when I read the Spanish version.
Please review and feel free to request any changes :+1:.

Improve Spanish readability for "Fix Like No One's Watching"

---

src/pages/the-bug-o-notation/index.es.md

This pull request contains a translation of the article `The “Bug-O” Notation` to Spanish.

Translate to Spanish: The “Bug-O” Notation

---

src/pages/a-complete-guide-to-useeffect/index.md

Change understaning to understanding

---

src/pages/a-complete-guide-to-useeffect/index.md

I assume this is what you meant? 🙃

Fix typo "pattern in broken" → "pattern is broken"

---

src/components/Signup.css

Found some redundant/overridden properties.

Styles fixes --> Signup.css

---

src/pages/react-as-a-ui-runtime/index.md

I think it's work defining anyway but the quotes seem to call for it. What do you think? Thanks!

Define persistent

---

src/pages/optimized-for-change/index.tr.md

index.tr.md - Translated to Turkish - Optimized for Change

---

src/pages/fix-like-no-ones-watching/index.tr.md

index.tr.md - Translated to Turkish - fix-like-no-ones-watching

---

src/pages/react-as-a-ui-runtime/index.md

Typo fix in the Conditions section

---

src/pages/fix-like-no-ones-watching/index.pl.md

Translate 'Fix Like No One’s Watching' to Polish

---

src/templates/blog-post.js

Fix Next/Prev overlapping

---

src/pages/a-complete-guide-to-useeffect/index.pt-br.md

translate `A Complete Guide to useEffect` to PT-BR

---

src/pages/writing-resilient-components/index.md

Fix typo - Writing Resilient Components

---

src/pages/writing-resilient-components/index.zh-hans.md

This pull request contains a translation of the article "Writing Resilient Components" to zh-hans.

translate `Writing Resilient Components` to Chinese

---

src/pages/a-complete-guide-to-useeffect/index.zh-hans.md

This pull request contains a translation of the article "A Complete Guide to useEffect" to Simplified Chinese.

Translate to Simplified Chinese: A Complete Guide to useEffect

---

src/pages/coping-with-feedback/index.id.md

In this Pull Request, I added Indonesian translation to Coping With Feedback Article.

Indonesian translation to coping-with-feedback

---

src/pages/coping-with-feedback/index.it.md

I'm not a translator. I did my best and i think it's quite readable.

Translate coping-with-feedback into Italian

---

src/pages/how-does-setstate-know-what-to-do/index.ko.md

Hi!
I made a translation for How Does setState Know What to Do? in korean.
It was a good reading for myself to study a bit more about react!
Cheers,
Hansol

Add korean translation for How Does setState Know What to Do?

---

src/pages/coping-with-feedback/index.pt-br.md

translate `Coping with Feedback` to PT-BR

---

src/pages/the-bug-o-notation/index.zh-hans.md

This PR translates [The “Bug-O” Notation](https://overreacted.io/the-bug-o-notation/) to Simplified Chinese.

Add Simplified Chinese translation: The “Bug-O” Notation

---

src/pages/the-bug-o-notation/index.zh-hant.md

As title, translate 'The “Bug-O” Notation' to Traditional Chinese.

Translate The “Bug-O” Notation to Traditional Chinese

---

src/pages/things-i-dont-know-as-of-2018/index.fr.md

assumer -> supposer
ça sonne -> ça a l'air
(et un peu de cosmétique)

[FR] Fix English->French calques / Correction de calques de l'anglais

---

src/pages/how-does-react-tell-a-class-from-a-function/index.pt-br.md

Add portuguese-brazil translation to "How does React tell a class from a function"

Translate "How does React tell a class from a function" to pt-br

---

src/pages/writing-resilient-components/index.md

This in Prop function (maybe i'm wrong)

Change this in a prop function

---

src/pages/coping-with-feedback/index.zh-hant.md

Translate coping with feedback to Traditional Chinese.

Translate coping with feedback to Traditional Chinese

---

src/pages/how-does-setstate-know-what-to-do/index.pt-br.md

I translate to Brazilian Portuguese the post: How Does setState Know What to Do?

Translate "How Does setState Know What to Do?" to pt-BR

---

src/pages/how-are-function-components-different-from-classes/index.pl.md

Translation "How Are Function Components Different from Classes?"  into Polish. Thanks to @boszkah for making the translation sounds more "polish(ed)"

Translation "How Are Function Components Different from Classes?" into Polish

---

src/pages/fix-like-no-ones-watching/index.id.md

This pull request contains a translation of the article "Fix Like No One’s Watching" to Bahasa Indonesia.

Translate to Bahasa Indonesia: Fix Like No One’s Watching

---

src/pages/react-as-a-ui-runtime/index.pt-br.md

Hi there. I aimed to do a translation using a similar way of writing of @gaearon's. Some words can be better understood if they remain in English, as there are many 'adopted' ones from English to Portuguese.
Let me know if you have any feedbacks.

pt-br translation of "React as a UI Runtime"

---

src/pages/things-i-dont-know-as-of-2018/index.de.md

Had a lot of fun doing this. I translated literally at first and then replaced a lot of things with more natural phrasings, but I think I got the overall mood - and I think it could be a blog post someone would write in German, not gonna lie, pretty proud of the translation :slightly_smiling_face:  Also a little surprised I was able to remember most of the key locations on a US keyboard, well done me.

Add german translation for "things i dont know"

---

src/pages/how-does-react-tell-a-class-from-a-function/index.nl.md

I really hope this is correct. I must say it is weird to write programming stuff in Dutch and I am always trying to decide when I should still use the English words or not. 
Learned a lot from trying to translate this though! Thanks @gaearon! If I do ever get a question about this subject at least I could **try** to answer it 😆.

Add Dutch translation to How Does React Tell a Class From a Function

---

src/pages/why-do-we-write-super-props/index.pl.md

This is my first PR here so I hope it's done right.

Add Polish translation for "Why Do We Write super(props)?"

---

src/pages/algebraic-effects-for-the-rest-of-us/index.md

Add missing 'if'

---

src/pages/algebraic-effects-for-the-rest-of-us/index.md

throw of getName was never reached. I suppose the intention was to have that throw.

Fix "Cannot read property 'add' of undefined".

---

src/pages/why-do-we-write-super-props/index.my.md

Improved some grammar mistakes and misuses. Fixed some extra white spaces, and stop placements.

small grammar fixes

---

src/pages/things-i-dont-know-as-of-2018/index.vi.md

This pull request contains a translation of the article "Things I Don’t Know as of 2018" to Vietnamese.

Translate to Vietnamese: Things I don't know as of 2018

---

gatsby-config.js
package.json
yarn.lock

Hi 👋
This PR adds adds a Gatsby plugin (full disclosure: written by me) that will create an e-book out of all posts on every build.
I wrote [this plugin](https://github.com/cowchimp/gatsby-plugin-ebook) especially for Overreacted because I wanted to read all the posts on a long flight ✈️, and I think this will be very convenient for a lot of other people as well.
If this PR is merged, a new file called `overreacted-ebook.epub` will be generated in the `/public` folder after every build.
I would be happy to modify the PR to add a link to the generated file from somewhere in the website itself if you'd like.
Thank you.

Create an Overreacted.io e-book on every build 📖

---

src/pages/how-does-setstate-know-what-to-do/index.tr.md

This pull request contains a translation of the article "How Does setState Know What to Do?" to Turkish.

Translate to Turkish: How Does setState Know What to Do?

---

src/pages/preparing-for-tech-talk-part-1-motivation/index.de.md

This pull request contains a translation of the article "Preparing for a Tech Talk, Part 1: Motivation" to German.

Translate to German: Preparing for a Tech Talk, Part 1: Motivation

---

src/pages/preparing-for-tech-talk-part-2-what-why-and-how/index.de.md

This pull request contains a translation of the article "Preparing for a Tech Talk, Part 2: What, Why, and How" to German.

Translate to German: Preparing for a Tech Talk, Part 2: What, Why, and How

---

src/pages/preparing-for-tech-talk-part-3-content/index.de.md

This pull request contains a translation of the article "Preparing for a Tech Talk, Part 3: Inhalt" to German.

Translate to German: Preparing for a Tech Talk, Part 3: Inhalt

---

src/pages/preparing-for-tech-talk-part-2-what-why-and-how/index.pt-br.md

Translate the article "Preparing for a Tech Talk, Part 2: What, Why, and How" to Brazilian Portuguese

translate 'Preparing for a Tech Talk, Part 2: What, Why, and How' to PT-BR

---

src/pages/how-does-the-development-mode-work/index.ko.md

This pull request contains a translation of the article "How Does the Development Mode Work?" to Korean.

Translate to Korean: How Does the Development Mode Work?

---

src/pages/react-components-unsubscribed.js

this is an unsubscribe confirmation page

add a page to confirm unsub

---

src/pages/my-decade-in-review/index.md

Both verbs need to be in the past tense.
Great doc!

Tense repair: "came and went"

---

src/pages/goodbye-clean-code/index.md

Lovely article, thanks for sharing :) I've enjoyed reading it being someone who was obsessed about clean code in the past.

Typo fixed (begrudgingly)

---

src/pages/goodbye-clean-code/index.ko.md

I revised a sentence in the paragraph, and translated that paragraph.
Any comments are welcome :) (especially from the first translator)

translate the remained paragraph

---

src/pages/goodbye-clean-code/index.pt-br.md

Fix typo in pt-BR translation

---

src/pages/goodbye-clean-code/index.es.md

Some small grammar corrections.

Corrections in "Goodby, Clean Code" Spanish translation

---

src/pages/a-complete-guide-to-useeffect/index.zh-hant.md

Fix typo of a-complete-guide-to-useeffect/index.zh-hant.md

 Corrections in "A Complete Guide to useEffect" Traditional Chinese translation 

---

src/pages/before-you-memo/index.ko.md

Translate 'Before You memo()' to Korean

---

src/pages/before-you-memo/index.zh-hans.md

this is the translation for 『Rendering optimizations that come naturally』

simplified Chinese translation

---

src/pages/before-you-memo/index.zh-hant.md

Before you memo - traditional Chinese translation

Before you memo - traditional Chinese translation

---

src/pages/react-as-a-ui-runtime/index.md

React as a UI Runtime

---

src/pages/before-you-memo/index.zh-hans.md

Update index.zh-hans.md - delete extra english words

---

src/pages/a-complete-guide-to-useeffect/index.es.md

This PR contains Spanish translation of "A Complete Guide to useEffect" article.

Translate "A Complete Guide to useEffect" to Spanish

---

src/pages/before-you-memo/index.es.md

Add missing Spanish translation to the Before you memo() post.

Translate 'Before You memo()' to Spanish

---

src/pages/how-does-the-development-mode-work/index.ko.md

fix: typo 

---

.gitignore
app/atom.xml/route.js
app/feed.js
app/page.js
app/rss.xml/route.js
package-lock.json
package.json

Would you consider adding back the rss/atom feed? Maybe something simple like this would do? Thanks :)

add atom/rss feed

---

app/feed.js
app/layout.js

Hey dan! Twitter removes your image :/

feat: migrate image to github

---

app/page.js

this fixes the text jitter on the hover animation
https://github.com/user-attachments/assets/5401cdd7-0c8e-443b-899f-d127b075f601

Fix hover animation

---

public/one-roundtrip-per-navigation/index.md

Howdy! I noticed that you accidentally a verb in the latest article, so figured I'd PR a fix. I _think_ the word you were looking for was "move", possibly.

Add a missing word in One Roundtrip Per Navigation
