gaearon/overreacted.io

src/utils/theme.css
closes #11 
related issue: https://github.com/gatsbyjs/gatsby/issues/9092#issuecomment-429928369
working on my local workspace.
=> Fix line highlight for long lines

src/utils/theme.css
As [mentioned on Twitter](https://twitter.com/HugoGiraudel/status/1069991265482223616), inline code are not properly highlighted when part of the selected text. It’s not too problematic when selecting an entire paragraph, but is a bit of an issue when selecting inline code directly, as it is not visually highlighted at all.
Removing these declarations should fix the issue without impacting the rest of the design. :)
=> Fix inline code selection styles

gatsby-config.js, src/components/SEO.js, src/pages/index.js, src/templates/blog-post.js
Fixes #4 
This PR adds an (automatic, mostly) twitter card capability, as well as some other general SEO goodness.
There's more to do here, but I didn't want to scope creep. Specifically, I think the following are worth doing:
- Move posts to content/ (better fit than pages), and cleans up directory structure a bit
- Add images/featured images to post, and inject them with GraphQL, pass to the SEO component (this will improve the twitter cards)
- This is set up, just didn't add any images yet
=> feat: add seo/twitter component for twitter cards, og tags, etc.

src/pages/my-wishlist-for-hot-reloading.md
"Support higher-order components" section.
- "But A HOC" capitalization
- "shouldn’t shouldn’t"
=> Fix typos in my-wishlist-for-hot-reloading.md

src/pages/why-do-hooks-rely-on-call-order.md
I wasn't thinking right in #42. Oops.
=> Fix typo: "sandwitch" -> "sandwich"

src/pages/why-do-hooks-rely-on-call-order.md
Fixes the form input variable names:
- `useNameInput ` -> `useNameFormInput`
- `useSurnameInput ` -> `useSurnameFormInput`
=> Fixes form input variable names

src/pages/why-do-hooks-rely-on-call-order.md
In "Why do react hooks rely on call order", Flaw #4: The Diamond Problem, there's a code example, 
the hook name is `useNetworkStatus` and not `useOnlineStatus`.
=> Change useOnlineStatus to useNetworkStatus in "Why do react hooks rely on call order"

src/pages/why-do-hooks-rely-on-call-order.md
This sentence "Granted, you probably won’t be tempted call useState('name') twice in the same components...." to this 
"Granted, you probably won’t be tempted to call useState('name') twice in the same components..."
Missing word was "to"
=> Fixed typo

gatsby-config.js
This adds a link back to the article for the RSS feed. This is useful so articles that are automatically published via ConverKit include a link to the source.
=> add link to bottom of RSS feed articles

gatsby-config.js
closes #67 
reference: https://www.gatsbyjs.org/packages/gatsby-plugin-feed/#how-to-use
=> RSS post summary use "spoiler" graphql field

gatsby-config.js
This solution is a little yucky because it relies on a regex based on slug conventions, but it seems to work. Fixes #72
=> Filters out non-english posts from RSS feed.

src/utils/typography.js
Tweaked the font-size override of code blocks inside paragraphs to match font-size of the surrounding text.
Before this change:
After this change:
- Run the site with `yarn dev`
- View a blog post with code snippets e.g. http://localhost:8000/why-do-hooks-rely-on-call-order/
- Verify inline code blocks match the font-size of surrounding text
Fixes #20
=> Amend font-size of <code> block inside <p> to 1rem

src/pages/confirm.js, src/pages/thanks.js
I noticed that there were a few deprecation errors when running `yarn start` so figured it was worth fixing them 🛠 
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/migrating-from-v1-to-v2.md#import-graphql-from-gatsby
=> fix global graphql deprecation warnings

src/templates/blog-post.js, src/utils/helpers.js
It's jarring that a translated post's header uses English for the date still. This tentative fix uses the ES402 / `Intl` API, when available, to turn the frontmatter’s date into a similar-choices localized date string based on the post's language.
Note that ES402 is supposted (enough) [across all major browsers](https://kangax.github.io/compat-table/esintl/)
=> L10n : use post locale for header date formatting

src/pages/why-do-we-write-super-props/index.sk.md, src/utils/i18n.js
This pull request contains a translation of the article "Why Do We Write super(props)?" to Slovak.
=> Translate to Slovak: Why Do We Write super(props)?

src/pages/why-do-hooks-rely-on-call-order/index.fr.md, src/utils/typography.js
Note to @gaearon: I took the liberty of adding a `.translation` variation of `<blockquote>` in the typography styles, as some (image) quoted content in that article begged for translation and the default block quote style looked way too massive for that use case (more like callout text).
=> French version of the “Why do React Hooks rely on call order?" article

src/utils/global.css
just a pet peeve: when in dark mode, scrolling outside the content shows a white background.
tested browsers that exhibit this issue: chrome (mac), safari (both iOS and mac), maybe others.
| ![before](https://user-images.githubusercontent.com/8649362/51796906-a6203e80-21e1-11e9-97ed-fad39b4cfbf7.png) | ![after](https://user-images.githubusercontent.com/8649362/51796908-a9b3c580-21e1-11e9-98b2-dd80f1ad23ec.png) |
|:---:|:---:|
| **before:** 😕 `⬜️⬛️`  | **after:** 👌 `⬛️⬛️`  |
=> fix overscroll background

gatsby-config.js, gatsby-node.js, package.json, src/pages/how-does-react-tell-a-class-from-a-function/index.fr.md, src/pages/how-does-setstate-know-what-to-do/index.fr.md, src/pages/the-elements-of-ui-engineering/index.fr.md, src/pages/why-do-hooks-rely-on-call-order/index.fr.md, src/templates/blog-post.js, src/utils/i18n.js, yarn.lock
Alternative to https://github.com/gaearon/overreacted.io/pull/143.
Should fix #141 and #101.
`gatsby-plugin-catch-links` takes care of linkifying internal posts. It actually seems to work pretty great out of the box and I didn't need to mess with it.
In order to automatically link translations, I'm gathering a list of what seems to be Markdown intra-domain links in `onCreateNode`. Then in `createPages` I do a pass to check if it looks like they're internal links that have translations. Translated pages receive an array of eligible hrefs in the page context. Finally, the post page does a pass over HTML to replace all links that we *know* have translations.
This shouldn't have much runtime or bundle size overhead. One post wouldn't pay for all translations I think. Only the linked ones from …
=> Linkify internal posts and use translations

gatsby-browser.js, package.json, src/utils/typography.js
1. Switching between translations of the same article doesn't jump the scroll anymore. (It also means going back and forth preserves scroll position which might be weird but IMO it's okay.)
2. Also fixes https://github.com/gaearon/overreacted.io/issues/195
=> Better scrolling behavior

src/pages/why-do-we-write-super-props/index.sk.md
Improves #159.
There were some typos and grammar issues in the original translation. I have also reworded some sentences.
=> Improve the Slovak translation of "Why Do We Write super(props)"

src/pages/why-do-we-write-super-props/index.zh-hant.md
Hi Dan, your articles are very valuable, I learned a lot. Thanks for sharing. 
This pull request contains a translation of the article "Why Do We Write super(props)?" to Traditional Chinese.
I have followed [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) this Chinese copywriting guidelines.
If there anywhere needs to be fixed, let me know. 
Again, thanks!!
=> Traditional Chinese translation of "Why Do We Write super(props)?"

.nowignore, now.json, package.json
This PR adds support to build this app inside Now and alias for each and every commit on master.
I test this on my own fork and [worked](https://github.com/arunoda/overreacted.io/commits/master) [well](https://github.com/arunoda/overreacted.io/commit/a80495f8463c49dac3bd3b90044da2dcafdd59f5#comments).
You'd also need to enable GitHub integration into your account.
For that, visit https://zeit.co/github
Ping me if you need additional info or changes.
=> Add support to build on now, deploy and alias

src/pages/react-as-a-ui-runtime/index.md
Hey Dan!
I was confused for a bit when saw original example — does `useReducer` preserve the state if `undefined` is returned? 
It doesn't, so having explicit default case is important and will prevent this confusion.
=> Add default return for the reducer example.

src/pages/why-do-we-write-super-props/index.nb.md, src/utils/i18n.js
Added a Norwegian translation to the Why Do We Write super(props)? article.
Translators notes:
- Added a link to the wikipedia article on gotcha's, as there is no Norwegian word that eloquently covers the full meaning. Furthermore, after discussing the word with a few Norwegian peers, we found that many of us didn't really have a good grasp of what the word meant (hence the link).
- A few words, e.g. parent, are left in English as their Norwegian counterpart doesn't really make sense, even to programmers.
If there's anything that needs changing, let me know :+1:
=> Added Norwegian (bokmål) translation to Why Do We Write super(props)?

.github/CODEOWNERS
This should automatically request a review from the appropriate language owner when a post is translated or has its translation updated. GitHub has [some docs](https://help.github.com/articles/about-code-owners/) about this file.
=> Add a CODEOWNERS file to automatically request reviews

gatsby-config.js
So I decided to play with a different RSS reader and I imported a few of the feeds that I'm subscribed to in the RSS application I normally use, and I noticed something... special about the RSS feed for overreacted.io:
After looking at the XML file for the RSS feed at https://overreacted.io/rss.xml I noticed that the posts lack the `<pubDate>` tag, so my RSS reader doesn't know at which date and time is the blog post published, therefore having an undefined behaviour.
This PR updates the serializer method used by gatsby-plugin-feed to fix this, as it seems that it is accessing the wrong variable when looking up for the publication date in the given query.
=> Fixes RSS feed lacking post dates

src/pages/how-does-setstate-know-what-to-do/index.fr.md, src/pages/how-does-setstate-know-what-to-do/index.ja.md, src/pages/how-does-setstate-know-what-to-do/index.md, src/pages/the-bug-o-notation/index.md, src/pages/why-do-hooks-rely-on-call-order/index.fr.md, src/pages/why-do-hooks-rely-on-call-order/index.md, src/pages/why-do-we-write-super-props/index.tr.md, src/pages/why-isnt-x-a-hook/index.es.md, src/pages/why-isnt-x-a-hook/index.md, src/utils/global.css
Changing from #200, separate branch
- Changes every instance of `js` to `jsx` for correct syntax highlighting
- Uses negative margin technique as seen on the React docs which makes the code align with the main blog text. On mobile, the block lies flush with the edge of the document which leaves more room for the code, resulting in less horizontal scrolling
=> Code block edits: JSX syntax highlighting, negative margins

src/pages/react-as-a-ui-runtime/index.md
Thanks for the excellently written article!
=> Fix typos: was => were (unreal conditional sentence), remove extra "be"

gatsby-config.js, src/components/Layout.js
When selecting the dark theme on Chrome on Android, the pink is very bright compared to the rest. So this PR sets the `<meta name="theme-color" />` based on the current theme. 
Gif:
=> Set '<meta name="theme-color" />' based on theme.

src/pages/making-setinterval-declarative-with-react-hooks/index.md
The code snippet used near the beginning of the post didn't provide inputs to `useEffect`, needlessly updating the callback after every render. The CodeSandbox demo linked next to the snippet does pass the inputs array.
This PR makes the code snippet consistent with the CodeSandbox demo.
=> Pass callback to useEffect updating savedCallback

src/templates/blog-index.js
The current per-locale index pages use a fixed-locale date formatting, instead of the locale-aware formatting used on blog posts. This harmonizes it.
=> Use localized date formats on language-based index pages

src/pages/why-do-we-write-super-props/index.pt-br.md
Just fixing a typo in the pt-BR version, "construto" => "construtor"
=> Fix typo "construtor"

src/components/Toggle.css
* Use transform to animate theme toggle for smoother animation
Using `transform: translateX()` is better than using `left` for animations, because browsers use sub-pixel interpolation when animation `transform` values:
* https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/
* https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/
* https://css-tricks.com/tale-of-animation-performance/
*Note:* I checked to make sure that toggling the switch still works on a touchscreen.
* Remove unnecessary css rules
Gatsby [uses autoprefixer with a default browserslist config](https://github.com/gatsbyjs/gatsby/blob/365b18cb77f299cfd18a756a30674859a77db641/docs/docs/browser-support.md#specify-what-browsers-your-project-supports-using-browserslist) …
=> More smooth theme toggle animation with transform

src/components/SEO.js
Open Graph uses the `property` attribute. Reference http://ogp.me/
=> fix: change og meta tags to property instead of name attribute

src/pages/writing-resilient-components/index.md
[_Mistakingly_](https://en.wiktionary.org/wiki/mistakingly) is in fact a word (TIL!), but the dictionaries I've checked suggest that [_mistakenly_](https://en.wiktionary.org/wiki/mistakenly) is the preferred form for the sense of "by accident, by mistake, in error (without intention to do so)".
Love the article, by the way!
=> mistakingly -> mistakenly

src/pages/writing-resilient-components/index.md
The text said `lint config config` which should just be `lint config`
=> Remove duplicated word in Writing Resilient Components

src/pages/react-as-a-ui-runtime/index.md
Fixed a typo on the code block
=> fix a typo `setCounter` -> `setCount`

src/pages/preparing-for-tech-talk-part-1-motivation/index.zh-hans.md
Original: `Preparing for a Tech Talk, Part **2**: What, Why, and How`
Translate: `做好技术分享，第**二**章：内容，原因和方法`
=> Fix typo in `(zh-cn)Preparing for a Tech Talk P1`

package.json, src/utils/js-to-jsx.js
It's so easy to forget to use \`\`\`jsx instead of \`\`\`js. As I'm noticing new posts forgetting, particularly in translations.
This will change every instance in blog posts on pre-commit.
=> js-to-jsx helper to run on pre-commit

src/pages/a-complete-guide-to-useeffect/index.pt-br.md, src/templates/blog-post.js, src/utils/i18n.js, src/utils/whitelist.js
Fixed some typos and added two paragraphs that were not translated.
Also, every link pointing to `https://reactjs.org` are now `https://pt-br.reactjs.org` thanks to the community!
=> Fix typos and add two translations [PT-BR]

src/pages/why-isnt-x-a-hook/index.pt-br.md
Fixed typo when reading the Portuguese translation.
=> Fix typo - Why isn't X a Hook [PT-BR]

src/pages/fix-like-no-ones-watching/index.pl.md
It's a grammatical error that makes polish readers a bit hard to grasp
=> Fix for the polish translation

src/utils/global.css
_Sorry, this is an OCD issue._
In dark mode, there is no 0.2 transparency on `<code>` tags, resulting in hiding the most of the `<a>`'s underline when there is a `<code>` inside of an `<a>`.
This made me look into transparency calculus (thanks for the opportunity), and according to this [Wikipedia article on transparency](https://en.wikipedia.org/wiki/Transparency_%28graphic%29), rgba(115,124, 153, 0.2) should render the same color on the dark background as the hsl(222, 14%, 25%) you are currently using.
Here you have a 'before' and 'after' screenshot.
PS: thanks for adding the dark mode, perfect for my bedtime stories
=> OCD: Fix <code> background in dark mode

src/pages/making-setinterval-declarative-with-react-hooks/index.md
I noticed that this post referred to the PR for the hooks eslint plugin because it wasn't ready at the time of writing, but now that it's ready, I propose that the link should point to the npm package (or maybe the github repo?)
=> Update link to eslint-plugin-react-hooks

src/pages/writing-resilient-components/index.md
This component is a functional component, and shouldn't need this.props as the props are destructed in the params. I am new to React and software development so this could be wrong! Thanks
=> Update file Writing Resilient Components

src/pages/preparing-for-tech-talk-part-1-motivation/index.fr.md
This corrects a small typo in the french translation of "Preparing for a Tech Talk, Part 1: Motivation".
=> Fix typo in fr translation of Tech talk part 1

src/components/Signup.css, src/components/Signup.js, src/utils/global.css
Found my self reading at night and was blinded by the bright white signup box at the bottom of the posts even while in dark mode. I have added styling to the background of the signup container and text to make it more in line with the rest of the sites styling while in dark mode. Please let me know if this needs any changes to meet your standards!
Would love to see this added to save others eyes 👁 👍 
Current:
Change in this PR:
=> Adding dark mode styling to the signup component

src/pages/goodbye-clean-code/index.md
=> Fixing typo on "Goodbye Clean Code"

LICENSE-code-snippets, LICENSE-posts
As per the discussion in https://github.com/gaearon/overreacted.io/issues/473#issuecomment-568909346,this PR adds a less restrictive license for code snippet.
Classic disclaimer that I'm not a lawyer, so I have no idea if this is legally sufficient or not, but seems like a reasonable set up to me hopefully!
=> Add less restrictive license for code snippets

src/components/Signup.js, src/pages/a-complete-guide-to-useeffect/index.md, src/pages/algebraic-effects-for-the-rest-of-us/index.md, src/pages/how-are-function-components-different-from-classes/index.md, src/pages/how-does-react-tell-a-class-from-a-function/index.md, src/pages/how-does-setstate-know-what-to-do/index.md, src/pages/how-does-the-development-mode-work/index.md, src/pages/react-as-a-ui-runtime/index.md, src/pages/the-elements-of-ui-engineering/index.md, src/pages/what-are-the-react-team-principles/index.md, src/pages/why-do-hooks-rely-on-call-order/index.md, src/pages/why-do-react-elements-have-typeof-property/index.md, src/pages/why-isnt-x-a-hook/index.md, src/templates/blog-post.js, yarn.lock
This adds a dynamic cta to any post with `cta: 'react'` in its markdown frontmatter.
The new form will subscribe people to a 7-day email sequence that delivers the epic [Writing Resilient Components post](https://overreacted.io/writing-resilient-components/) one email at a time.
=> cta for resilient react components email course

src/components/Signup.js
Validation is not preset in email subscription form. I tried using empty name and invalid email address, it still accepts. I was thinking it would be better if a front end level validation was there. Just added required attribute in the form inputs.
=> Email subscription form - validation

src/pages/a-complete-guide-to-useeffect/index.zh-hant.md
Hi there, 
I happen to notice there might be a better way to translate 'functional form updater' to zh-tw.
'Form' as in 'essays in book form'; instead of form as in 'filling in a form.'
Also this translation aligns with react doc (https://zh-hant.reactjs.org/docs/hooks-reference.html#functional-updates) better :)
=> Translation of 'functional updater form'

src/pages/making-setinterval-declarative-with-react-hooks/index.zh-hans.md
`L:171` and `L:202` is using the same URL currently.
Correct URL in `L:202` from https://codesandbox.io/s/mz20m600mp to https://codesandbox.io/s/329jy81rlm
=> zh-hans translation: fix CodeSandbox URL in "Counter demo with hooks"

app/AutoRefresh.js, app/layout.js, package-lock.json, package.json, public/npm-audit-broken-by-design/index.md, watcher.js
I use `<MDXRemote>` so by default updating the content does not trigger Fast Refresh. To fix that, I'm adding a little manual socket server that triggers `router.refresh()` whenever I edit the Markdown files.
=> Add a DEV-only watcher for content files

public/a-chain-reaction/index.md
Noticed that log of Greeting props in recent post was raw `alice` object instead of `{ person: alice }`
Also not this pr related, but avatar on the site was ruined cause the link to now closed twitter acc, I think
=> Fix JSX props log for Greeting

app/[slug]/page.js
Bug: On mobile device. Visit the [overreacted.io](https://overreacted.io/), click on any article containing an image. The image in the article will not display, you will have to refresh the article to display the image.
Issue: https://github.com/gaearon/overreacted.io/issues/827
Need to handle adding the article slug to the img's src in page.js, add img to MDXRemote.
=> Update page.js to Fix Bug Error displaying images in posts

public/npm-audit-broken-by-design/index.md
Replace a no-break-space, which was causing the heading to format incorrectly, with a normal space.
=> Fix formatting in index.md

package.json
I help maintain [npm-run-all2](https://github.com/bcomnes/npm-run-all2), the community fork of npm-run-all and noticed you were still running the original, but sadly neglected version. This fixes a bunch of small issues and keeps on top of security updates. Beyond that, it's just the npm-run-all we all love with maintenance.
=> Switch to npm-run-all2

public/jsx-over-the-wire/index.md
I'm not sure if we need to pass the `postId` to the list components since we will be fetching posts based on the recentPostIds.
=> Remove unused property `postId` for PostList route

public/jsx-over-the-wire/index.md
Points to the correct `<PostListRouteViewModel />` when the url matches `'/screen/post-list'`.
=> JSX Over The Wire: PostDetailsRouteViewModel → PostListRouteViewModel

public/react-for-two-computers/index.md
Just fixed a minor typo in the code snippet. By the way, thanks for the insightful and well-written article!
=> fix: typo (`json` -> `primitives`)

public/react-for-two-computers/index.md
Just noticed this typo while reading. Fantastic article by the way!
=> Fix typo (`interpert` -> `interpret`)

public/react-for-two-computers/index.md
`retext-smartypants` incorrectly determines that the first quote should be the closing one in this sentence:
```md
"*Some* of them do."
```
Fixing this by forcing opening quote with backticks.
=> fix: quotes in React for Two Computers

app/[slug]/markdown.css, app/[slug]/page.js, package.json
This pull request fixes #851 by adding support for tables within the Markdown renderer.
- install remark-gfm and update package.json
- configure MDXRemote in app/[slug]/page.js to render tables
- add css styles for tables, th and td
Before:
After:
=> feat(markdown): add support for tables using remark-gfm
